/*
 *
 * @package com.lobobrowser.cobra.data.db
 * @license http://lobobrowser.com/about/license
 * @copyright (c) 2015 Lobo Browser Team
 *
 */
package com.lobobrowser.cobra.data.db;

/**
 * A class modelling foreign key relationships between tables of the
 * <code>PUBLIC</code> schema
 */
@javax.annotation.Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.5.0"
    },
    comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

  // -------------------------------------------------------------------------
  // IDENTITY definitions
  // -------------------------------------------------------------------------

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final org.jooq.UniqueKey<com.lobobrowser.cobra.data.db.tables.records.PermissionsRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
  public static final org.jooq.UniqueKey<com.lobobrowser.cobra.data.db.tables.records.CookiesRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;
  public static final org.jooq.UniqueKey<com.lobobrowser.cobra.data.db.tables.records.GlobalsRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
    public static final org.jooq.UniqueKey<com.lobobrowser.cobra.data.db.tables.records.PermissionsRecord> CONSTRAINT_C = createUniqueKey(
            com.lobobrowser.cobra.data.db.tables.Permissions.PERMISSIONS, com.lobobrowser.cobra.data.db.tables.Permissions.PERMISSIONS.FRAMEHOST,
            com.lobobrowser.cobra.data.db.tables.Permissions.PERMISSIONS.REQUESTHOST);
    public static final org.jooq.UniqueKey<com.lobobrowser.cobra.data.db.tables.records.CookiesRecord> CONSTRAINT_6 = createUniqueKey(
            com.lobobrowser.cobra.data.db.tables.Cookies.COOKIES, com.lobobrowser.cobra.data.db.tables.Cookies.COOKIES.HOSTNAME, com.lobobrowser.cobra.data.db.tables.Cookies.COOKIES.NAME);
    public static final org.jooq.UniqueKey<com.lobobrowser.cobra.data.db.tables.records.GlobalsRecord> CONSTRAINT_3 = createUniqueKey(
            com.lobobrowser.cobra.data.db.tables.Globals.GLOBALS, com.lobobrowser.cobra.data.db.tables.Globals.GLOBALS.NOTACOLUMN);
  }
}
