/*
 *
 * @package com.lobobrowser.cobra.data.db
 * @license http://lobobrowser.com/about/license
 * @copyright (c) 2015 Lobo Browser Team
 *
 */
package com.lobobrowser.cobra.data.db;

/**
 * Convenience access to all tables in PUBLICF
 */
@javax.annotation.Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.5.0"
    },
    comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table PUBLIC.PERMISSIONS
   */
  public static final com.lobobrowser.cobra.data.db.tables.Permissions PERMISSIONS = com.lobobrowser.cobra.data.db.tables.Permissions.PERMISSIONS;

  /**
   * The table PUBLIC.COOKIES
   */
  public static final com.lobobrowser.cobra.data.db.tables.Cookies COOKIES = com.lobobrowser.cobra.data.db.tables.Cookies.COOKIES;

  /**
   * The table PUBLIC.GLOBALS
   */
  public static final com.lobobrowser.cobra.data.db.tables.Globals GLOBALS = com.lobobrowser.cobra.data.db.tables.Globals.GLOBALS;
}
